//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_STATUSHISTORY
    {
        public System.Guid STATUSHIST_ID { get; set; }
        public System.Guid COMP_ID { get; set; }
        public System.DateTime ACTIVATED_ON { get; set; }
        public System.DateTime DEACTIVATED_ON { get; set; }
        public System.Guid MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_ON { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
    }
}
